CREATE TABLE EPAYSCH.DEEE_ATCL (
  TITLE VARCHAR2(64) NOT NULL,
  AUTHOR VARCHAR2(64) NOT NULL,
  EDITOR VARCHAR2(64) NOT NULL,
  TIME_CREATE TIMESTAMP DEFAULT to_timestamp('1000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
  TIME_MODIFY TIMESTAMP DEFAULT to_timestamp('1000-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
  CONTENT CLOB NOT NULL,
  VERSION VARCHAR2(8) NOT NULL,
  ID VARCHAR2(32) NOT NULL,
  CONSTRAINT DEEE_ATCL_PK PRIMARY KEY (ID)
)
TABLESPACE EPAYDB;
